// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKEV0WMpwVqzSHyVxlG0VYJUxkOqKeuTc',
    appId: '1:566952332194:web:add01798340a8f46bd40fb',
    messagingSenderId: '566952332194',
    projectId: 'eldercare-3831b',
    authDomain: 'eldercare-3831b.firebaseapp.com',
    storageBucket: 'eldercare-3831b.firebasestorage.app',
    measurementId: 'G-YJ1M0XL40H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK0kg3US3PUhRzdXkBe-waaOSv25fVAiw',
    appId: '1:566952332194:android:c91869724e17bd34bd40fb',
    messagingSenderId: '566952332194',
    projectId: 'eldercare-3831b',
    storageBucket: 'eldercare-3831b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIWWZxm3cA6jaDhxZ1fKiIOY-_ro1_MtM',
    appId: '1:566952332194:ios:018eac51071272b7bd40fb',
    messagingSenderId: '566952332194',
    projectId: 'eldercare-3831b',
    storageBucket: 'eldercare-3831b.firebasestorage.app',
    iosBundleId: 'com.example.eldercareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIWWZxm3cA6jaDhxZ1fKiIOY-_ro1_MtM',
    appId: '1:566952332194:ios:018eac51071272b7bd40fb',
    messagingSenderId: '566952332194',
    projectId: 'eldercare-3831b',
    storageBucket: 'eldercare-3831b.firebasestorage.app',
    iosBundleId: 'com.example.eldercareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKEV0WMpwVqzSHyVxlG0VYJUxkOqKeuTc',
    appId: '1:566952332194:web:537361b6a10adbbfbd40fb',
    messagingSenderId: '566952332194',
    projectId: 'eldercare-3831b',
    authDomain: 'eldercare-3831b.firebaseapp.com',
    storageBucket: 'eldercare-3831b.firebasestorage.app',
    measurementId: 'G-8P0PKLY9T3',
  );
}
